name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /www/wwwroot/digitalAuction_fe
            git fetch origin
            git checkout main
            git pull
            docker build -t digitalauction .
            docker stop digitalauction-container || true
            docker rm digitalauction-container || true
            docker run -d --name digitalauction-container -p 4000:4173 digitalauction
