name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/digitalAuction_fe
            echo "${{ secrets.ENV_FILE }}" > .env
            git fetch origin
            git checkout main
            git pull
            docker build -t digitalauction .
            docker stop digitalauction-container || true
            docker rm digitalauction-container || true
            docker run -d --name digitalauction-container -p 4000:4173 digitalauction
